GET_ALL_PRODUCE_QUERY = "SELECT produce_id AS id, produce_name AS name, description, price, season FROM Produce;"
GET_PRODUCE_BY_ID_QUERY = "SELECT produce_id AS id, produce_name AS name, description, price, season FROM Produce WHERE produce_id = %s;"
GET_ALL_FARMING_PRACTICES_QUERY = "SELECT practice_id AS id, practice_name, description FROM FarmingPractices;"
GET_ALL_COMMUNITY_EVENTS_QUERY = "SELECT event_id AS id, event_name, event_date, description FROM CommunityEvents;"
INSERT_CONTACT_QUERY =  "INSERT INTO contact (name, email, message) VALUES (%s, %s, %s)"